.TH OPENLASE "9" "December 2012" "laserboy" "User Commands"
.SH NAME
openlase \- Open realtime laser show graphics toolkit.
.SH SYNOPSIS
.B openlase
.br
openlase home page: <http://marcansoft.com/>
.br
.SH COPYRIGHT
Copyright \(co 2012 Hector Martin
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
